[package]
name = "wasm"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[package.metadata.ft]
targets = ["wasm32-unknown-unknown"]
