[package]
name = "mac"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[package.metadata.ft]
targets = ["x86_64-apple-darwin"]
